### ISSUE TITLE
Launch doesn't finish, but all suites did

### ISSUE THREAD

**Issue by BorisOsipov** [BorisOsipov/wdio-reportportal-reporter#1]

**Comment by BorisOsipov** [comment]
Won't fix. Workaround add to wdio.conf.js
```
  onComplete: async function (exitCode, config, capabilities) {
    return new Promise(resolve => setTimeout(resolve, 5000));
  },
```

and hope that all promises resolve.

**Comment by thephilwells** [comment]
Isn't there something we can poll on the API to wait for rather than guessing 5 seconds will cover it?

**Comment by BorisOsipov** [comment]
@thephilwells 
yes probably we can poll launch status by report portal API from `onComplete` hook. For that we have to share `launchId` and you can add additional logic to `onComplete` hook. I can share `launchId` easily if you need. Does it need for you?

But the right way is create additional service for wdio for do that.
I have a plan to follow such approach for new wdio v5 reporter.

**Comment by BorisOsipov** [comment]
@thephilwells alos I believe when you run you test on CI the tests launch will close on RP till this time and 5 sec that's nothing on tests run time

**Comment by thephilwells** [comment]
Accessing the status using a `launchId` value would be perfect! I wonder how I'd know the right `launchId` value to ask for. That can't be set by the reportportal plugin, can it?

**Comment by thephilwells** [comment]
I know it won't affect test timing. It's not really a huge deal, just kind of a code smell to guess at 5 seconds. Much better to definitely know the report transaction is closed before wdio kills the process.

**Comment by BorisOsipov** [comment]
@thephilwells 
>That can't be set by the reportportal plugin, can it?
not.`launchId` sets by RP server.
But I know how to share it with you if you need. I will add such feature this week stay tunned.

**Comment by BorisOsipov** [comment]
> It's not really a huge deal, just kind of a code smell to guess at 5 seconds.  

yeah, I know it is weird and ridiculous. Let's get rid of this.

**Comment by BorisOsipov** [comment]
@thephilwells 

Now you can use special service or implement wait in wdio hook https://github.com/BorisOsipov/wdio-reportportal-reporter#wait-until-launch-finished

See updated docs diff https://github.com/BorisOsipov/wdio-reportportal-reporter/pull/39/files

**Comment by thephilwells** [comment]
Amazing! Thanks for the quick solution!

**Comment by igerasimov23** [comment]
Following errors occurs in console when:
`onComplete: async function (exitCode, config, capabilities) {
    await reporter.waitLaunchFinished();
  }`
AND reportportal reporter disabled in wdio conf: `  reporters: ['spec', 'dot', /*'reportportal'*/],
`

> TypeError:
 Cannot read property 'helpers' of undefined
    at Function.<anonymous> (/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/wdio-reportportal-reporter/build/reporter.js:57:51)
    at Generator.next (<anonymous>)
    at /Users/208821/Projects/np-cooking/api/test/e2e/node_modules/wdio-reportportal-reporter/build/reporter.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/wdio-reportportal-reporter/build/reporter.js:3:12)
    at Function.waitLaunchFinished (/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/wdio-reportportal-reporter/build/reporter.js:55:16)
    at Object.onComplete (/Users/208821/Projects/np-cooking/api/test/e2e/wdio.conf.js:395:20)
    at Launcher._callee$ (/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/webdriverio/build/lib/launcher.js:366:47)
    at tryCatch (/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/208821/Projects/np-cooking/api/test/e2e/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13

**Comment by BorisOsipov** [comment]
@thephilwells Did you get a chance to test it? any issues?

**Comment by thephilwells** [comment]
I got it working. When I tried `"wdio-reportportal-reporter": "^0.0.21"` in package.json, the library didn't update. It worked when I pinned my version specifically to v0.0.21.

**Comment by BorisOsipov** [comment]
@thephilwells thanks. Actually service does the same underhood
https://github.com/BorisOsipov/wdio-reportportal-service/blob/5c3f3dc2cb37162d85eba442bfa481077689b8a3/index.js#L6-L16

**Comment by thephilwells** [comment]
Is the plan to keep it supported in both places? Or should I switch out to the service before that method gets cleaned out here?

**Comment by BorisOsipov** [comment]
>Is the plan to keep it supported in both places?

yes

**Comment by luuizeduardo** [comment]
@BorisOsipov I have been using the latest version of reporter and service but I'm getting an error when I run my test suit:

![image](https://user-images.githubusercontent.com/36016665/60684143-5f123580-9e72-11e9-8f7f-e9e371ad0dbc.png)

This is my wdio config file (I have supressed some information about token and project):
`
const reportportal = require('wdio-reportportal-reporter');
const RpService = require("wdio-reportportal-service");

const conf = {
  reportPortalClientConfig: {
    token: 'my-token',
    endpoint: 'http://localhost:8080/api/v1',
    launch: 'TEST',
    project: 'my-project',
    tags: ["FUNCTIONAL"],
    mode: 'DEFAULT',
    debug: false,
  },
  reportSeleniumCommands: false,
  autoAttachScreenshots: false,
  seleniumCommandsLogLevel: 'debug',
  screenshotsLogLevel: 'info',
  parseTagsFromTestTitle: false,
};

exports.config = {
  runner: 'local',
  hostname: 'localhost',
  port: 4444,
  path: '/wd/hub',
  specs: [
    './test/specs/**/*.js'
  ],
  maxInstances: 10,
  capabilities: [{
    maxInstances: 5,
    browserName: 'chrome',
  }],
  logLevel: 'info',
  bail: 0,
  baseUrl: 'http://automationpractice.com',
  waitforTimeout: 10000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  framework: 'mocha',
  services: [[RpService, {}]],
  reporters: [[reportportal, conf]],
  mochaOpts: {
    ui: 'bdd',
    timeout: 60000
  }
}
`

Find bellow the dependencies of my project:

`
"devDependencies": {
    "@wdio/cli": "^5.10.9",
    "@wdio/local-runner": "^5.10.9",
    "@wdio/mocha-framework": "^5.10.8",
    "@wdio/sync": "^5.10.8",
    "chromedriver": "^75.0.0",
    "wdio-reportportal-reporter": "^5.0.1",
    "wdio-reportportal-service": "^5.0.1"
  }
`

**Comment by BorisOsipov** [comment]
@luuizeduardo create issue https://github.com/BorisOsipov/wdio-reportportal-reporter/issues/68 for this.
