### ISSUE TITLE
Not possible to pass a value to `level` that is valid in TypeScript

### ISSUE THREAD

**Issue by caiogondim** [BorisOsipov/wdio-reportportal-reporter#109]
## The problem

It's not possible to pass a value to `level` that is valid in TypeScript, since `LEVELS` enum is not exported.

![image](https://user-images.githubusercontent.com/33044/76104186-e59e8a00-5fa0-11ea-969c-3bf429f5514d.png)

## Details

Possible ideas to fix this problem:
- Expose the constants
- Use this pattern https://github.com/microsoft/TypeScript/issues/17690#issuecomment-361215664

## Code To Reproduce Issue

```js
import ReportPortalReporter from 'wdio-reportportal-reporter';
ReportPortalReporter.sendLogToTest('foobar', 'INFO');
```

**Comment by BorisOsipov** [comment]
Hi @caiogondim 

Thank you for reporting this.

I am not familiar with typings at all.
If you know how to fix I will appreciate if you make the PR.

>Expose the constants

I don't think it is good to expose all constants because there are a lot of internal things - so we need to extact logs level somehow.

**Comment by caiogondim** [comment]
> I don't think it is good to expose all constants because there are a lot of internal things - so we need to extact logs level somehow.

I agree with that. But in the case for `LEVELS` it's external, so maybe it makes sense to export it. I will push a PR.
