### ISSUE TITLE
Can tests correspond to scenarios , not steps

### ISSUE THREAD

**Issue by HardKode** [BorisOsipov/wdio-reportportal-reporter#130]
## The problem
Actually a question  /  enhancement request
I am using wdio with cucumber , reporting to a report portal server .
As of now , the scenario steps are reported as tests where  I was expecting it to be scenario based .

## Environment

* WebdriverIO version: v.5
* wdio-reportportal-version version: 5.2.3
* Node.js version: 12.14
* WDIO Testrunner and version(mocha\cucumber\jasmine): 5.18.6
* Additional wdio packages used (if applicable):

**Comment by BorisOsipov** [comment]
@HardKode have you tried with `cucumberNestedSteps: true` config option?
and what is your RP version?

**Comment by HardKode** [comment]
Report portal : Build: 5.2.2
yes, I have , my config looks like this : ( ps: i am using a proper token)
 {
    "reportPortalClientConfig": {
      "token": "00000000-0000-0000-0000-00000000000",
      "endpoint": "",
      "launch": "automationtests-launch",
      "project": "automationtests",
      "description": "auto tests",
      "mode": "DEFAULT",
      "debug": false,
      "tags": [
        "local-automationtests",
        {
          "key":"suite",
          "value":"regression"
        }
      
      ]
    },
    "reportSeleniumCommands": false,
    "seleniumCommandsLogLevel": "debug",
    "screenshotsLogLevel": "info",
    "parseTagsFromTestTitle": true,
    "autoAttachScreenshots": true,
    "cucumberNestedSteps": true,
    "autoAttachCucumberFeatureToScenario": true
  }

**Comment by BorisOsipov** [comment]
@HardKode can you share screenshot from RP with comments what is wrong? I can't understand what is wrong

**Comment by HardKode** [comment]
![image](https://user-images.githubusercontent.com/3990708/93512449-b1fece00-f8fa-11ea-8d4c-45f042896d69.png)

**Comment by HardKode** [comment]
if you look  at the total , it says 2 , i only have one scenario in that simple test

**Comment by HardKode** [comment]
When i look at the base JS agent : https://github.com/reportportal/agent-js-cucumber , there is  section that suggest you can change what is a test :  steps or scenarios .

Step reporting configuration
By default, this agent reports the following structure:

feature - SUITE
scenario - TEST
step - STEP
You may change this behavior to report steps to the log level by enabling scenario-based reporting:

feature - TEST
scenario - STEP
step - log item
To report your steps as logs, you need to pass an additional parameter to the agent config: "scenarioBasedStatistics": true

{
  "scenarioBasedStatistics": true
}
This will report your your steps with logs to a log level without creating statistics for every step.

**Comment by BorisOsipov** [comment]
@HardKode update wdio-reportportal-reporter to 5.2.6 and wdio-reportportal-service to 5.2.5

5.2.3 doesn't support cucumberNestedStep.

![image](https://user-images.githubusercontent.com/6514276/93513711-ee4c2180-f92e-11ea-8dd2-39829dd08e81.png)

**Comment by HardKode** [comment]
hi @BorisOsipov  , thanks .  I will proceed with those updates and report back . 
You have been incredibly responsive , appreciate it

**Comment by HardKode** [comment]
Hello @BorisOsipov  .
I can confirm that the version update was effective and I seem to know receive scenario based tests.
Thanks again

**Comment by BorisOsipov** [comment]
OK close then
