### ISSUE TITLE
Launch status shows in progress and need to manually finish it. 

### ISSUE THREAD

**Issue by amit-manerkar-by** [BorisOsipov/wdio-reportportal-reporter#134]
## The problem

Briefly describe the issue you are experiencing or the feature you want) Tell us what you were trying to do and what happened instead.

## Environment

* WebdriverIO version: 6.10.0
* wdio-reportportal-version version: 6.1.2
* Node.js version: 14.15
* WDIO Testrunner and version(mocha\cucumber\jasmine): mocha 6.8.0
* Additional wdio packages used (if applicable):

## Details

After the suite is run, launch status shows "In Progress" Status. Also different launches are created for each describe block (suite).
Is there any functionality to keep all suites in a single launch?

**Comment by BorisOsipov** [comment]
@amit-manerkar-by cannot reproduce the issue. Could you share a sample project?

**Comment by amit-manerkar-by** [comment]
@BorisOsipov  https://github.com/amit-manerkar-by/wdiosample

![image](https://user-images.githubusercontent.com/69339196/101916504-06a9a080-3bed-11eb-9eb2-120ad4928d1c.png)

Issue 1:
Launch remain in progress post execution
Issue 2:
New Launch is created per describe block (suite).

**Comment by BorisOsipov** [comment]
@amit-manerkar-by Thank you for example it makes easier to help.

It is an error in your config. Services declaration must be `services: [['selenium-standalone'], [RpService, {}]],` or even simple `services: [['selenium-standalone'], [RpService]],`. 

![image](https://user-images.githubusercontent.com/6514276/101933954-f9d97c80-3bed-11eb-8dae-27b0f28a0eb1.png)

**Comment by nklemiata** [comment]
Oh god, this answer has finally helped after a day of search-and-try!!! 
@[BorisOsipov](https://github.com/BorisOsipov), thank you so much for it and for the wdio-reportportal-reporter!!
