### ISSUE TITLE
How to setup Custom attribute name and Custom Project name from Env variables 

### ISSUE THREAD

**Issue by Shivin89** [BorisOsipov/wdio-reportportal-reporter#148]
## The problem

Hi Boris,

I wanted to implement WebdriverIO having RP custom attributes name and project name from my System env variables.

I am not able to figure out how we can customize that where attributes get assigned from system variables.

I was able to do that for Java, .net project but could do it for WebdriverIO (could not find how assignment is done in typescript)

like below screenshot 
![image](https://user-images.githubusercontent.com/22401226/113351953-794fa080-92f0-11eb-8195-8acf808dcf64.png)

Here you see I am setting the release_version attribute from my system env variable, same with the name of the test.

The end goal is to integrate it with ZAPI to update the zephyr test case automatically which requires Release Number, Test Cycle Number, Project Name.

But right now I want to set These attributes from the system variable.

example of Java 
![image](https://user-images.githubusercontent.com/22401226/113352616-5c679d00-92f1-11eb-9323-a9405f5326e1.png)

## Environment

* WebdriverIO version:
* wdio-reportportal-version version:
* Node.js version:
* WDIO Testrunner and version(mocha\cucumber\jasmine):
* Additional wdio packages used (if applicable):

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by BorisOsipov** [comment]
Hi @Shivin89 

Am I right, you want to add attributes to the *launch* from env variables?

**Comment by Shivin89** [comment]
Yes, that is correct Launch one,  as per the screen shot attached

**Comment by Shivin89** [comment]
I’m actually customizing your repo to add these attributes from env
variable and There is a need to integrate zapi to automatically update
zephyr test case.
We have customized Java with cucumber. Dot net. And also jasmine (both
attributes and zapi)

It’s only wendriverIO left

**Comment by BorisOsipov** [comment]
@Shivin89 it could be done by the reporter config in `wdio.conf.js`. Like this:

```
const reportportal = require('wdio-reportportal-reporter');
const RpService = require("wdio-reportportal-service");

const conf = {
  reportPortalClientConfig: { 
...
    attributes: [{key: process.env.QA_RELEASE_VERSION}, {key: process.env.QA_TEST_CYCLE}],
  },
...
};

exports.config = {
  // ...
  services: [[RpService, {}]],
  reporters: [[reportportal, conf]],
  // ...
};
```

**Comment by BorisOsipov** [comment]
@Shivin89 
>We have customized Java with cucumber. Dot net. And also jasmine (both
attributes and zapi)

could you add links to corresponding commits in cucumber\java\jasmine repos? It will make easier to understand what you exactly want to achieve

**Comment by Shivin89** [comment]
But wdio.conf.js is not part of Repo, That will be used by product teams to config RP.
I am customizing your repo which doesn't have this file (I will upload the customized version of this repo to Artifactory and from there the product teams will use this customized repo).

Is there a way to customize at the repo level? Like what we did in other plugins

**Comment by BorisOsipov** [comment]
>Is there a way to customize at the repo level? 

Nope. But it is not so hard to add. you can add such variables by PR in https://github.com/BorisOsipov/wdio-reportportal-service/blob/master/src/index.js#L65

**Comment by Shivin89** [comment]
> @Shivin89
> 
> > We have customized Java with cucumber. Dot net. And also jasmine (both
> > attributes and zapi)
> 
> could you add links to corresponding commits in cucumber\java\jasmine repos? It will make it easier to understand what you exactly want to achieve

That is a customized plugin that our product teams are using, I can definitely  share my bitbucket repo for the cucumber plugin  and Jasmin.

Here in this repo, you will find how we have assigned attributes from system variables.

https://stash.cdk.com/projects/PEOEQA/repos/engqa.reportportal.cucmber6.agentt/browse
https://stash.cdk.com/projects/PEOEQA/repos/engqa.reportportal.jasminejs/browse

**Comment by BorisOsipov** [comment]
@Shivin89 seems it is repos in private bitbucket.

**Comment by Shivin89** [comment]
> @Shivin89 seems it is repos in private bitbucket.

Yes, This is our customized version of the plugin . 
https://stash.cdk.com/projects/PEOEQA/repos/engqa.reportportal.cucmber6.agentt/browse/src/main/java/com/epam/reportportal/cucumber/AbstractReporter.java

This file has the attribute under startLaunch();

**Comment by Shivin89** [comment]
Where are you setting the attributes and project name?

**Comment by Shivin89** [comment]
@BorisOsipov 
I need to add a customized Test Case Id to the Test (If the user has provided a Test ID in their test like QUALITY-123456), 
right now it displays like this 

![image](https://user-images.githubusercontent.com/22401226/113448556-f04c6e00-93b0-11eb-8d4d-d401113da043.png)
 I want to have something like this 
![image](https://user-images.githubusercontent.com/22401226/113448697-2e499200-93b1-11eb-8fb9-1a8c6f2dc2c9.png)


so I added the following code under onTestStart(test, type = TYPE.STEP) method

if (test.title.includes("||") && test.title.split("||").length > 0) {
      testStartObj.testCaseId = test.title.split("||")[0];
    }

Added this under entities 
 public testCaseId?: string;
![image](https://user-images.githubusercontent.com/22401226/113448374-92b82180-93b0-11eb-81ce-33a48027a13b.png)

![image](https://user-images.githubusercontent.com/22401226/113448407-a2376a80-93b0-11eb-909c-8df86b697c8d.png)

Will this work?
How to add a Test Case ID in the WebDriverIO test? So that it shows customized ID

**Comment by BorisOsipov** [comment]
@Shivin89 https://github.com/BorisOsipov/wdio-reportportal-service/blob/master/src/index.js#L24

**Comment by Shivin89** [comment]
@BorisOsipov  I was able to assign custom Testcase ID from Test scripts to the QA report Portal.

I am facing an issue with a POST request (With respect to Zapi integration). I hope you could help me with that. Here is my code, it logs till  console.log("before axios") and then nothing happens. Can you see if this POST request is correct?

const postRequest = async (url, rquestData) => {
    var myHeaders = {}
    myHeaders['Content-Type'] = "application/json";
    myHeaders["Authorization"] = "Basic " + JIRA_BASIC_KEY;

    console.log("before axios")
    let postResponse = await axios.post(url, rquestData, { headers: myHeaders }, { timeout: 60000 })
        .then(data => {
            console.log("inside post")
            console.log(LEVEL.TRACE, url)
            console.log(LEVEL.TRACE, rquestData)
            //console.log(LEVEL.TRACE, data.data)
            return (data.data)
        })
        .catch(error => {
            console.log(error)
            return (null);
        });
    console.log(JSON.stringify(postResponse))
    return postResponse
};

**Comment by BorisOsipov** [comment]
@Shivin89 Sorry, I have no clue what is wrong with your request. Please, post it to stackoverflow.
