### ISSUE TITLE
A failed suite is shown as passed in the History view for launch

### ISSUE THREAD

**Issue by itayTipalti** [BorisOsipov/wdio-reportportal-reporter#155]
## The problem

Hi,
When I have a failed child item, it is shown as a "failed" and I expect that the Suite history will be shown as a failed item and not a passed, like I added in the pictures:
![image](https://user-images.githubusercontent.com/83645807/119511068-bda06f80-bd7a-11eb-829d-29cbdc472332.png)
![image](https://user-images.githubusercontent.com/83645807/119511300-f50f1c00-bd7a-11eb-80a8-b793ccc293a1.png)

## Environment

* WebdriverIO version: 6
* wdio-reportportal-version version: 6.4
* Node.js version:14.16.0
* WDIO Testrunner and version(mocha\cucumber\jasmine):Jasmine: 7.5.2
* Additional wdio packages used (if applicable):wdio-reportportal-reporter,wdio-reportportal-service

## Details
as shown in the problem description

**Comment by BorisOsipov** [comment]
Hello @itayTipalti

Thanks for reporting this. I'll see how to fix it.

**Comment by itayTipalti** [comment]
@BorisOsipov 
it works, thanks alot!
