### ISSUE TITLE
Request failed with status code 400

### ISSUE THREAD

**Issue by Alek5andr** [BorisOsipov/wdio-reportportal-reporter#161]
## The problem

Testrunner spits out "Request failed with status code 400" error, when reportportal service and reporter are attached in WDIO config:
```
Error: Request failed with status code 400
    at C:\Users\alek5andr\Documents\wdio-rp-integration-demo-master\node_modules\reportportal-js-client\lib\rest.js:27:23
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

## Environment
* Windows 10 x64
* WebdriverIO version: 7
* wdio-reportportal-service/reporter version: 7.0.0
* Node.js version: 14.17.2
* WDIO Testrunner and version: mocha\jasmine 7.7

## Details

I have managed to launch ReportPortal application on local machine using Docker - UI is accessible at http://localhost:8081/ui
I have tried to attach reportportal service and reporter to my WDIO project. But I get "Request failed with status code 400" error, when tests are run.
Next I have tried this project https://github.com/iAutomator/wdio-rp-integration-demo from GitHub. I have updated its WDIO version to 7 and have made it synchronous. I have adjusted ReportPortal configuration according to my ReportPortal application, reduced `main.js` test to login feature and have launched it successfully. But still I receive "Request failed with status code 400" error in the output. And what makes me sad more is that no additional info what is bad in the request! Setting ReportPortal config field `debug` to `true` does not extend details of the issue.

## Modified files from mentioned project to reproduce the error
```
// package.json
{
// ...
  "devDependencies": {
    "@wdio/cli": "^7.7.4",
    "@wdio/jasmine-framework": "^7.7.3",
    "@wdio/local-runner": "^7.7.4",
    "@wdio/sync": "^7.7.4",
    "chromedriver": "^91.0.1",
    "dotenv": "^8.0.0",
    "wdio-chromedriver-service": "^7.1.1",
    "wdio-reportportal-reporter": "^7.0.0",
    "wdio-reportportal-service": "^7.0.0"
  }
}
```

```
// main.js
// ...
describe(suiteName, () => {
    it(testName, () => {
        rp.sendLog(logLevel, logMsg)

        LoginScreen.open()
        LoginScreen.username = process.env.RP_USERNAME
        LoginScreen.password = process.env.RP_PASSWORD
        LoginScreen.submit()
    })
})
```

```
// LoginScreen.js
// ...
class _LoginScreen {
    open() {
	console.log('rpAddress = ' + rpAddress);
        browser.url('http://' + rpAddress);
    }
// ...
}

const LoginScreen = new _LoginScreen()

module.exports = LoginScreen
```

May the issue be with proxy? If so, in what application proxy should be managed then?
Or what is the cause? And how to get more detailed information about the error?

**Comment by BorisOsipov** [comment]
Hi @Alek5andr 

> And what makes me sad more is that no additional info what is bad in the request!

Client lib prints errors that server returns. If it doesn't provide the error message you will see the error like this. There is nothing to do from client side.

>May the issue be with proxy? If so, in what application proxy should be managed then?

I believe, if you ran RP on localhost proxy should not affect at all. Currently proxy is supported for unix like OS by standart env variables HTTP_PROXY\etc. If you need ability to configure proxy manually in config please create feature request - I will add it.

>Or what is the cause? And how to get more detailed information about the error?

Probably RP portal logs should help you to investigate this issue.
If you have doubts in your wdio configs you can use my MWE https://github.com/BorisOsipov/rp-empty
