### ISSUE TITLE
Add Description to Suite Not Possible

### ISSUE THREAD

**Issue by dwentland24** [BorisOsipov/wdio-reportportal-reporter#167]
## The problem

I use mocha as test runner and want to add some information to the description of a suite. Like session to browserstack or link to bitrise build. I could not find a way to accomplish such a thing. Do I miss anything here or would this be a feature request? 

## Environment

* WebdriverIO version: 7.9.0
* wdio-reportportal-version version: 7.2.1
* Node.js version: 15
* WDIO Testrunner and version(mocha\cucumber\jasmine): mocha 9.0.3
* Additional wdio packages used (if applicable):  wdio-junit-reporter, spec-reporter, local-runner

**Comment by BorisOsipov** [comment]
@dwentland24 yes it is impossible now. I'll see on this week how we can implement it.
