### ISSUE TITLE
Launch doesnot finish even after successful execution of test in webdriverIO on report portal

### ISSUE THREAD

**Issue by sakshi-tawani** [BorisOsipov/wdio-reportportal-reporter#172]
## The problem

Briefly describe the issue you are experiencing or the feature you want) Tell us what you were trying to do and what happened instead.

## Environment

* WebdriverIO version:
* wdio-reportportal-version version:
* Node.js version:
* WDIO Testrunner and version(mocha\cucumber\jasmine):
* Additional wdio packages used (if applicable):

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by BorisOsipov** [comment]
Can't reproduce without example.
