### ISSUE TITLE
Skipped scenarios are marked as failed when 'cucumberNestedSteps' is 'true'

### ISSUE THREAD

**Issue by PriyankaSarangi** [BorisOsipov/wdio-reportportal-reporter#173]
## The problem
I'm using wdio with cucumber and the tests are reporting to a report portal server. 
When I set the below two combinations of these values 
1 - `cucumberNestedSteps=true` and `autoAttachCucumberFeatureToScenario=true`
2 - `cucumberNestedSteps=true` and `autoAttachCucumberFeatureToScenario=false`
Report portal is reporting a scenario as failed in its dashboard when few steps in the scenario are passed and few are skipped.
The status of the scenario is `skipped` in `afterScenario` hook in `wdio.conf.js` file
How can I mark the scenario as skipped?

## Environment

* WebdriverIO version: 6.1.14
* wdio-reportportal-reporter version: 7.4.0
* Node.js version: 16.5.0
* WDIO Testrunner and version(mocha\cucumber\jasmine): 6.1.14
* Additional wdio packages used (if applicable):

## Details
For example if I have a scenario like this:
Scenario: scenario headline
       ✓ Given I open a random website
       ✓ When I wait on something
        - And perform some action
        - Then I skip this step
I want this scenario to be marked as a `skipped` in the main dashboard instead of failed.

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by BorisOsipov** [comment]
Seems reasonable. Feel free to make a PR. Suite status calculates here https://github.com/BorisOsipov/wdio-reportportal-reporter/blob/master/lib/reporter.ts#L158

**Comment by BorisOsipov** [comment]
@PriyankaSarangi it is default RP behavior. To disable it you have to pass issue with type "NOT_ISSUE" along with endTestItem RQ.

**Comment by BorisOsipov** [comment]
I mean it requires changes in reporter too

**Comment by PriyankaSarangi** [comment]
@BorisOsipov `EndTestItem` is already receiving the issue type as "NOT_ISSUE" including the status of the test (i.e, SKIPPED in this case) from here https://github.com/BorisOsipov/wdio-reportportal-reporter/blob/master/lib/reporter.ts#L236 
But still in the report-portal the scenario is tagged as `To Investigate`

**Comment by BorisOsipov** [comment]
@PriyankaSarangi it is endTestItem for cucumber step . You see `To Investigate` for scenario. You have to send issue with type "NOT_ISSUE" for scenario endTestItem RQ too

**Comment by PriyankaSarangi** [comment]
@BorisOsipov Thank you for your responses. I have created this PR here : https://github.com/BorisOsipov/wdio-reportportal-reporter/pull/175 to address the issue.

**Comment by BorisOsipov** [comment]
@PriyankaSarangi That's awesome. I will review\merge\release it ETA within a week.
