### ISSUE TITLE
Failed test case screenshots not to be pushed to reportportal.io using the afterStep hook

### ISSUE THREAD

**Issue by vaibhavjagdale** [BorisOsipov/wdio-reportportal-reporter#176]
## The problem

Failed test case screenshots not to be pushed to reportportal.io using the afterStep hook

## Environment

* WebdriverIO version:7.13.2
* wdio-reportportal-version version:7.4.1
* Node.js version:v14.17.4
* WDIO Testrunner and version(mocha\cucumber\jasmine):7.13.2

## Details
I am trying to push failed test case screenshots to reportportal.io. I followed https://webdriver.io/docs/wdio-reportportal-reporter/
Don't know somehow stepData[one of parameter for afterStep hook] is undefined or null. and I don't know what is extra thing I am missing in this configuration.
## Code To Reproduce Issue [ Good To Have ]
**rp.config.json**

`
{
"reportPortalClientConfig": {
      "token": "",
      "endpoint": " ",
      "launch": "UI_TEST",
      "project": "automation",
      "mode": "DEFAULT",
      "debug": false,
      "description": "test",
    },
    "reportSeleniumCommands": false, 
    "seleniumCommandsLogLevel": "debug",
    "enableScreenshotsReporting": true,
    "screenshotsLogLevel": "info"
}
`

**afterStep**

`
 afterStep: function (uri, feature, { error, result, duration, passed }, stepData, context) {
     if (!passed) {
        let failureObject = {};
        failureObject.type = 'afterStep';
        failureObject.error = error;
        failureObject.title = `${stepData.step.keyword}${stepData.step.text}`;
        const screenShot = global.browser.takeScreenshot();
        let attachment = Buffer.from(screenShot, 'base64');
        reportportal.sendFileToTest(failureObject, 'error', "screnshot.png", attachment);
    }
  }
`

**Comment by vaibhavjagdale** [comment]
Solved

**Comment by ztshashi** [comment]
@vaibhavjagdale - What was the resolution for this issue?

**Comment by vaibhavjagdale** [comment]
@ztshashi I tried this.
check method definition afterStep hook in config file generated by wdio init.
```
const reportportal = require('wdio-reportportal-reporter');

afterStep: async function(step, scenario, result, passed, error,duration) {
    if (!result.passed) {
       const screenShot = await global.browser.takeScreenshot();
       let attachment = await Buffer.from(screenShot, 'base64');
       await reportportal.sendFile('error', "screnshot.png", attachment);
   }
 }
````
