### ISSUE TITLE
Report portal reporting the scenario steps as test in the count

### ISSUE THREAD

**Issue by splurgeop** [BorisOsipov/wdio-reportportal-reporter#182]
## The problem

The reportportal is reporting each step as a test whereas it should report it as a single test

## Environment

* WebdriverIO version:
* wdio-reportportal-version version: wdio-reportportal-reporter : 7.4.1 and wdio-reportportal-service : 7.3.1
* Node.js version: 16.13.0
* WDIO Testrunner and version(mocha\cucumber\jasmine): Cucumber @cucumber/cucumber: 7.3.1
* Additional wdio packages used (if applicable):
* reportportal build: Build: 5.6.0

## Details

While integrating the report portal with wdio, have seen that the status of scenario thats being sent to report portal as number of steps.i.e the steps are converting to test case rather than the scenario.

Below is the rp config

 reportPortalClientConfig: {
        token: process.env.REPORTPORTAL_TOKEN,
        endpoint: "XXXXXXXXXXXXXXX/api/v1",
        launch: "E2E Tests",
        project: "edmc_e2e_tests",
        mode: "DEFAULT",
        debug: false,
        description: "EDMC - E2E Tests",
        attributes: [
            { key: "Type", value: "E2E Tests" },
            { key: "Branch", value: process.env.CI_COMMIT_REF_SLUG },
            { key: "Repository", value: process.env.CI_PROJECT_NAME },
            { key: "Team", value: process.env.CI_PROJECT_NAMESPACE },
            { key: "Tags Executed", value: EnvironmentParams.getEnvironmentParams().tagToExecute },
            { key: "Browser", value: EnvironmentParams.getEnvironmentParams().defaultBrowser },
        ],
        autoAttachScreenshots: true,
        parseTagsFromTestTitle: true,
        cucumberNestedSteps: true,
        autoAttachCucumberFeatureToScenario: true,
        sanitizeErrorMessages: true,
        enableScreenshotsReporting: true,
        screenshotsLogLevel: 'info',
    }

![image](https://user-images.githubusercontent.com/18133300/177323747-9ddd914b-401f-4f91-b2e2-0f1bfe7851d2.png)

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by BorisOsipov** [comment]
@splurgeop could not reproduce. As I see your config is wrong. It must look like:
```
const config = {
  reportPortalClientConfig: {
    token: process.env.REPORTPORTAL_TOKEN,
    endpoint: 'XXXXXXXXXXXXXXX/api/v1',
    launch: 'E2E Tests',
    project: 'edmc_e2e_tests',
    mode: 'DEFAULT',
    debug: false,
    description: 'EDMC - E2E Tests',
    attributes: [],
  },
  autoAttachScreenshots: true,
  parseTagsFromTestTitle: true,
  cucumberNestedSteps: true,
  autoAttachCucumberFeatureToScenario: true,
  sanitizeErrorMessages: true,
  enableScreenshotsReporting: true,
  screenshotsLogLevel: 'info',
};
```
Pay attention `reportPortalClientConfig` doesn't include reporter options like `cucumberNestedSteps\autoAttachScreenshots\etc`
