### ISSUE TITLE
Logs and Screenshot not being sent if failure occurs at Before Feature level and Run is marked as Interrupted 

### ISSUE THREAD

**Issue by mtalreja** [BorisOsipov/wdio-reportportal-reporter#183]
## The problem

I am trying to use the cucumber with WDIO to Send log and Screenshot into report portal and the logs, image does not post.

## Environment

* WebdriverIO version: 7.16.13
 "wdio-reportportal-reporter": "^7.4.2",
 "wdio-reportportal-service": "^7.3.1",
* Node.js version: v16.13.2
* WDIO Testrunner and version(mocha\cucumber\jasmine): cucumber
* Additional wdio packages used (if applicable):

## Details
Hello all! My question is that I am trying to integrate rp to my project. I have successfully install rp but I am facing an issue on how to send a screenshot and logs to rp. 

I have a Scenario where I am Stopping the execution at beforeFeature() using cucumber. 

Say you need to run the execution only when you are able to access the application, lets the application you are trying to **Test** does not Launch, so in that Case I Stop my execution using  "process.exit(1);" and logs the Failure reason before exiting the process.

## Code To Reproduce Issue [ Good To Have ]
 beforeFeature: async function (uri, feature) {
        console.log('*** Executing Before Feature ***');
        try {
            //login Code
        } catch (error) {
            await TakeScreenshot(feature.name);
            const pageTitle = await GetBrowserTitle();
            console.error(`App is not up, found ${pageTitle}`);

            let attachment = await Buffer.from(global.currentScreenShot, 'base64');
            await reportportal.sendLog('error', `App is not up, found ${pageTitle}`);
            await reportportal.sendFile('error', `${feature.name}.png`, attachment, 'image/png', `App is not up, found ${pageTitle}`);
            await DeleteBrowserSession();
            process.exit(1);
        }
    },

## Screenshot
![image](https://user-images.githubusercontent.com/15871223/182656313-a217a658-9151-496f-aaef-c3e9d0b684d6.png)
![image](https://user-images.githubusercontent.com/15871223/182656366-fc90a44c-20f5-4516-b825-34ad9d1c9312.png)

**Comment by BorisOsipov** [comment]
Hi @mtalreja 

>I Stop my execution using "process.exit(1);"
> Run is marked as Interrupted

You stop not only test execution but also stop the reporter (it runs at the same process as test). If you stop the reporter abnormally it is impossible to finish RP test item and TestItem is marked as Interrupted and whole run is marked as Interrupted.

>the logs, image does not post

The same reason. If you stop reporter abnormally - don't expect it to work properly.

Generally, you should not "stop" test execution by "process.exit()" but throw any exception. Then setup RP to mark such failures as  "Infrastructure issue".
If you call "process.exit()" expect unexpected issues with reporter\services.

**Comment by mtalreja** [comment]
@BorisOsipov  
True I agree on this we should not use process.exit(), however I tried throwing exception from beforeFeature still the execution continues and the test case execution starts thus not able to achieve what is expected.

**Comment by BorisOsipov** [comment]
@mtalreja You can try throw `SevereServiceError`. I am not sure would it work for regular hooks, but I guess it will.

See in docs
https://webdriver.io/docs/customservices/#service-error-handling

**Comment by mtalreja** [comment]
@BorisOsipov I tried above approach still not working :(

**Comment by BorisOsipov** [comment]
@mtalreja maybe move that code in native Cucumber hooks and skip scenario?
https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/hooks.md#skipping-in-a-before-hook

btw it is a bit offtop :) I close the issue.
