### ISSUE TITLE
Does not support retry option

### ISSUE THREAD

**Issue by igerasimov23** [BorisOsipov/wdio-reportportal-reporter#2]
when user sets retry in webdriverIO suite, reportportal does not display that actual test were in retry

**Comment by BorisOsipov** [comment]
Wdio doesn't propagate to reporter is it retry or first test run. So it can't be implemented without hacks.

**Comment by igerasimov23** [comment]
I was able to use retry option using JS client of reportportal that way:
``` rpClient.startTestItem({
      description: testCaseName,
      name: testCaseName,
      start_time: rpClient.helpers.now(),
      type: "STEP",
      retry: true
    }, launchObjTempId, suiteObj.tempId); ```
and Reportportal was successfully displaying that test was in retry. I did not have much time to see your implementation `wdio-reportportal-reporter` but I saw that you use RPClient as well so probably there option to pass `retry: true` flag as well. Do you have any thoughts? If you don't have time I will try to do it myself to try `retry` option. Can you give me hints how to do it using your implementation?

**Comment by BorisOsipov** [comment]
@igerasimov23 There is no problem to report data to RP by `client-javascript`. 

There is issue with wdio. It doesn't send info is this test run is retry or not.
For example [test start event](https://github.com/BorisOsipov/wdio-reportportal-reporter/blob/00f18ef98ec4b06eac04ad5474d3d43238d7ade7/lib/reporter.js#L100)
looks like:
```
{ type: 'test:start',
  title: 'with failing test',
  parent: 'A failing Suite',
  fullTitle: 'A failing Suite with failing test',
  pending: false,
  file:
   'C:\\work\\wdio-reportportal-reporter\\testWip\\fixtures\\specs\\failing.js',
  cid: '0-0',
  specs:
   [ 'C:\\work\\wdio-reportportal-reporter\\testWip\\fixtures\\specs\\failing.js' ],
  event: 'test:start',
  runner: { '0-0': { browserName: 'chrome' } },
  uid: 'with failing test3',
  parentUid: 'A failing Suite2',
  specHash: '45d58304e8edae31e4e4461ce6e268e6' }
```

So I can't get know is it retry or not. I need to think and make some research how handle it better. I have some ideas(e.g. check parent type and handle retries by such info, it also give some advantages to imporove logging), but I will be able to check only next week.

P.S. Also with retries sample I ran into your issue https://github.com/BorisOsipov/wdio-reportportal-reporter/issues/4. Wdio-reporter create wrong test suite\ test case structure and can't finish launch correctly. It should be handled and fixed too.

**Comment by BorisOsipov** [comment]
Also to be on the same page, under retries you mean following:

```
describe('A failing Suite', () => {
  it('with failing test', async function () {
	//retries count 
    this.retries(2);
    await browser.url('http://webdriver.io/');
    const title = await browser.getTitle();
    expect(true).to.be.equal(false);
  });
});
```

or are there other wdio retries feature?

**Comment by igerasimov23** [comment]
Yes, this is what I meant by retries.  But wdio also supports retries for hooks(such as before test, but it's a more complicated I think to implement). I did not test your new implementation with feature flags yet, will do it over weekends or next week and then will think about retries as well. We ran into issue #4 with retries as well when we were trying implement custom JUnit reporter for reportportal

**Comment by BorisOsipov** [comment]
@igerasimov23 	
I went through RP docs\samples and mocha docs. So I think it is impossible to implement retries support. I won't waste time to it more.

Issues:
1) RP requires set `retry=true` for the all attempts to start test with retries even first. So when wdio-mocha runs test I should already now are there going to be retries or not - but I can't get such info see 2
2) Wdio-mocha doesn't provides any info that test will be retried or not.
[Also there is bug in mocha retries feature itself ](https://github.com/mochajs/mocha/issues/2188) 
3) Wdio-mocha(actually it's mocha itself) fires retry events strange. For example:
```
1 Start suite:
2 	Start test
3	Start test
4	Start test
5	Finish test
6 Finish suite.
```
So I don't know which status(and error message and stacktrace) have tests on lines 2-4.	No info at all.

I can suggest couple workarounds:
- ignore all retries and report only last test result. Actually it is ok from my point of view. I don't see any disadvantages or implementation issues.
- create additional test items for retries - but it increase overall tests count in the launch and make I don't like such way.

What do you think?

**Comment by igerasimov23** [comment]
I think on this stage I'm fine with 
> ignore all retries and report only last test result. Actually it is ok from my point of view.
But problem is test status in progress and never finishes. Do you know what should I change in reporter.js file in order get instead of:
``` 
1 Start suite:
2 	Start test
3	Start test
4	Start test
5	Finish test
6 Finish suite.
```
in ReportPortal:
```
1 Start suite:
2 	Start test (don't report)
3	Start test(don't report)
4	Start test
5	Finish test
6 Finish suite.
```
Any ideas?

**Comment by BorisOsipov** [comment]
It is gonna be a bit different
```
1 Start suite:
2 	Start test 
3	Start test(don't report)
4	Start test(don't report)
5	Finish test
6 Finish suite.
```

is it ok?

**Comment by BorisOsipov** [comment]
@igerasimov23 
Can you check, I've added it in `0.0.9` and it works on my tests.
To enable it set option `enableRetriesWorkaround: true` in wdio.conf.js

**Comment by igerasimov23** [comment]
I tried and it works fine. 
Just minor comments:
1. In RP we still see logs from all runs and not from first one  only, but I think it's very good fo debugging purposes
2. If screenshots are enabled sometimes session still in progress due #7

**Comment by BorisOsipov** [comment]
Good news!

>If screenshots are enabled sometimes session still in progress due #7

I don't think it is relarted. `sendFileToLastFailedTest` can't be reason to prevent test\launch to stop correctly. 
Can you add screen how it looks like? I am interesting in not launch screen but specific suite\test that is still in progress.

**Comment by igerasimov23** [comment]
I'm posting for expected result I think how it should be when all async call will be completed:
```
afterTest:  function (test) {
    //logging Pass or Fail for test
    (test.passed) ? reporter.sendLogToLastFailedTest('debug', `******* TEST '${test.title}' PASSED ******* `)
      : reporter.sendLogToLastFailedTest('debug', `******* TEST '${test.title}' FAILED ******* `);

    if (test.passed === false) {
      const screenshot =  browser.saveScreenshot();
      browser.call(function () {
        reporter.sendFileToLastFailedTest('info', 'failed.png', screenshot);
      })
      browser.pause(10000)
    }
  },
```

logs from console: 
``` before suite
******************************************************
***** Verify footer is displayed -feature footer *****
******************************************************[16:43:49]  DATA		{"url":"https://cooking.stg.nytimes.com/"}
[16:43:51]  DATA		{"using":"css selector","value":".nytc---surveybanner---container"}
[16:43:51]  DATA		{}
Attempt to send file to failed item fails. There is no failed test yet.
Attempt to send log to failed item fails. There is no failed test yet.
******************************************************
***** Verify footer is displayed -feature footer *****
******************************************************[16:43:57]  DATA		{"url":"https://cooking.stg.nytimes.com/"}
[16:43:57]  DATA		{"using":"css selector","value":".nytc---surveybanner---container"}
[16:43:57]  DATA		{}
Attempt to send file to failed item fails. There is no failed test yet.
Attempt to send log to failed item fails. There is no failed test yet.
******************************************************
***** Verify footer is displayed -feature footer *****
******************************************************[16:44:03]  DATA		{"url":"https://cooking.stg.nytimes.com/"}
[16:44:21]  DATA		{"using":"css selector","value":".nytc---surveybanner---container"}
F[16:44:21]  DATA		{}
[16:44:26]  DATA		{}
------------------------------------------------------------------
[chrome  mac #0-0] Session ID: d16ab8fe-0cbe-4989-82b8-bf1482ad66de
[chrome  mac #0-0] Spec: /Users/208821/Projects/np-cooking/api/test/e2e/test/features/footer/test-footer.js
[chrome  mac #0-0] Running: chrome on mac
[chrome  mac #0-0]
[chrome  mac #0-0] test footer
[chrome  mac #0-0]   1) Verify footer is displayed -feature footer
[chrome  mac #0-0]
[chrome  mac #0-0]
[chrome  mac #0-0] 1 failing (39s)
```
look at output `Attempt to send file to failed item fails. There is no failed test yet.
Attempt to send log to failed item fails. There is no failed test yet.` is there after each failed test
Screenshot:
<img width="1377" alt="screen shot 2018-10-01 at 4 46 54 pm" src="https://user-images.githubusercontent.com/15241367/46315111-7e55fc80-c59a-11e8-8c41-47c3b8312bfd.png">

Now Attaching console output when after test does not have wait time:
```
afterTest:  function (test) {
    //logging Pass or Fail for test
    (test.passed) ? reporter.sendLogToLastFailedTest('debug', `******* TEST '${test.title}' PASSED ******* `)
      : reporter.sendLogToLastFailedTest('debug', `******* TEST '${test.title}' FAILED ******* `);

    if (test.passed === false) {
      const screenshot =  browser.saveScreenshot();
      browser.call(function () {
        reporter.sendFileToLastFailedTest('info', 'failed.png', screenshot);
      })
    }
  },
```
before suite
******************************************************
***** Verify footer is displayed -feature footer *****
******************************************************[16:49:19]  DATA		{"url":"https://cooking.stg.nytimes.com/"}
[16:49:20]  DATA		{"using":"css selector","value":".nytc---surveybanner---container"}
[16:49:20]  DATA		{}
Attempt to send file to failed item fails. There is no failed test yet.
******************************************************
***** Verify footer is displayed -feature footer *****
******************************************************[16:49:23]  DATA		{"url":"https://cooking.stg.nytimes.com/"}
[16:49:24]  DATA		{"using":"css selector","value":".nytc---surveybanner---container"}
[16:49:24]  DATA		{}
******************************************************
***** Verify footer is displayed -feature footer *****
******************************************************[16:49:26]  DATA		{"url":"https://cooking.stg.nytimes.com/"}
[16:49:27]  DATA		{"using":"css selector","value":".nytc---surveybanner---container"}
[16:49:27]  DATA		{}
F[16:49:35]  DATA		{}


0 passing (20.00s)
1 failing

1) test footer Verify footer is displayed -feature footer:
test should fail: expected false to be true
running chrome on mac
```
only one time we see: `Attempt to send file to failed item fails. There is no failed test yet.`

and screenshot:
<img width="696" alt="screen shot 2018-10-01 at 4 57 46 pm" src="https://user-images.githubusercontent.com/15241367/46315359-37b4d200-c59b-11e8-9f9d-6b9446081f74.png">

<img width="1400" alt="screen shot 2018-10-01 at 4 59 13 pm" src="https://user-images.githubusercontent.com/15241367/46315409-5f0b9f00-c59b-11e8-842b-6fed00c7a235.png">
<img width="1377" alt="screen shot 2018-10-01 at 4 59 00 pm" src="https://user-images.githubusercontent.com/15241367/46315410-5f0b9f00-c59b-11e8-90e7-3fce8dc9d76c.png">

**Comment by BorisOsipov** [comment]
About "Attempt to send file to failed item fails. There is no failed test yet." message. It is ok to see in your log because of wdio behaviour:

```
1 Start suite:
2 	Start test 
	Execute afterTest
3	Start test retry(don't report)
	Execute afterTest
4	Start test retry(don't report)
	Execute afterTest
5	Finish test
6 Finish suite.
```
So it executes `afterTest` after each retry. And when it calls first\second times actually there is no failing test and I can't evaluate test id to attach file..

**Comment by igerasimov23** [comment]
I understand that but if you look at second screenshot from RP, when I did not have wait time in AfterTest hook, it posted two screenshots and two custom logs from afterTest hook. But when I had wait time in afterTest hook it posted 1 screenshot and one log - I think this is how it suppose to be and this is the same what you were mentioned as well:

> So it executes afterTest after each retry. And when it calls first\second times actually there is no failing test and I can't evaluate test id to attach file..

**Comment by BorisOsipov** [comment]
First of all, you don't need waits in your afterTest hook. Also you don't need browser.call. `reporter.sendFileToLastFailedTest` is sync function.

Why it adds two logs? it is easy to explain.
By default sendFileToLastFailedTest implementation waits 2 sec to get failed test id. So if your tests are fast the last two or three events from `sendFileToLastFailedTest` call can fit in 2 secs, find the same failed test and add screen.

**Comment by igerasimov23** [comment]
I was thinking about retries more again, if you are using RPClient as well, then why `wdio-reportportal-reporter` can not not support retries the same way as RPClient. I tried to use RPClient straight in code and it works well. I added only one parameter to it:
```
beforeTest: function (test) {
    let testCaseName = test.title;

    //reporting
    stepObj = rpClient.startTestItem({
      description: testCaseName,
      name: testCaseName,
      start_time: rpClient.helpers.now(),
      type: "STEP",
      retry: true
    }, launchObjTempId, suiteObj.tempId);
```
Test:
```
describe('test footer', function () {
  let count = 0;
  this.retries(2);

  beforeEach(() => {
    browser.navigateTo();
  }, 2);

  it('Verify footer is displayed -feature footer', function () {
    if (count > 1) {
      assert.isTrue(true, 'tets Passed')
    } else {
      count++;
      assert.isTrue(false, 'tets failed')
    }
  });

  it('Verify footer is displayed 2 -feature footer', function () {
    assert.isTrue(false, 'tets failed')
  });
});
```
<img width="1417" alt="screen shot 2018-10-12 at 6 41 47 pm" src="https://user-images.githubusercontent.com/15241367/46897083-af61e700-ce4e-11e8-87f5-8f3953276279.png">
<img width="1410" alt="screen shot 2018-10-12 at 6 41 58 pm" src="https://user-images.githubusercontent.com/15241367/46897084-af61e700-ce4e-11e8-9978-2e991b6178d8.png">
<img width="1393" alt="screen shot 2018-10-12 at 6 43 50 pm" src="https://user-images.githubusercontent.com/15241367/46897122-d6b8b400-ce4e-11e8-9c13-7f0e5296bc20.png">
<img width="1394" alt="screen shot 2018-10-12 at 6 42 21 pm" src="https://user-images.githubusercontent.com/15241367/46897085-af61e700-ce4e-11e8-9731-bbf73d472af7.png">

Looks like we don't have to do anything as Report Portal will take of defining into retry group and mark it pass if last test will pass or otherwise. Let me know your thoughts? or am I missing anything in the way you implemented `wdio-reportportal-reporter`

**Comment by BorisOsipov** [comment]
Almost the same info as in https://github.com/BorisOsipov/wdio-reportportal-reporter/issues/2#issuecomment-425876788

You are missing that calling code from wdio hooks and implementing wdio-reporter are different things. Completely different. Wdio runners call wdio hooks and propogate events to reporters not the same.

In reporter I have events:
```
1 Start suite:
2 	Start test
3	Start test
4	Start test
5	Finish test
6 Finish suite.
```
You may noticed there is no `Finish test` events for `Start test` №1 and №2.
So I can't get know what happened with test №1 and №2 - neither stackrace nor status.
What should I send to RP? I think nothing to send.

**Comment by igerasimov23** [comment]
@BorisOsipov Finally WDIO has feature to report number of retries in which test currently in. I think it will be a good enhancement for this plugin and long waiting feature for me personally to finally support retry option.
https://github.com/webdriverio/webdriverio/pull/4722
```
afterTest: function (test, context, { error, result, duration, passed, retries }) {
    console.log(test._retries);
    console.log(test._currentRetry);
  },
```

**Comment by BorisOsipov** [comment]
@igerasimov23 The problem is hook calls aren't reporter events... 
As I said in https://github.com/BorisOsipov/wdio-reportportal-reporter/issues/2#issuecomment-429552531

> You are missing that calling code from wdio hooks and implementing wdio-reporter are different things. Completely different. Wdio runners call wdio hooks and propogate events to reporters not the same.

https://github.com/webdriverio/webdriverio/pull/4722 PR doesn't help at all as I see to help me in reporting test retries to RP. 

Btw I will check, maybe in recent wdio improvements smth changes that may help in retries reporting or maybe reuse this hooks improvements somehow..

**Comment by igerasimov23** [comment]
I looked at afterTest() hook and for each retry it reports failure msg if retry test fails.Am I missing something? Are you saying we cannot use info from afterTest() hook and pass it to reportportal?

**Comment by BorisOsipov** [comment]
>Are you saying we cannot use info from afterTest() hook and pass it to reportportal?

1) yes. Reporter and hooks isn't the same. Reporter uses events from runner described here - 
https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-reporter#test-events and in these events no info about retries. Also as I am not mistaken wdio isnt fired events when test retry happens at all. Need check now, mb something changes.

2) Maybe we can use this somehow, e.g. notify reporter from afterTest() about errors as we do in e,g, screenshots attachments, but I am not sure - need investigations. But It will be crutches...

From my point of view, if you really suffer without retries support, we need to collect requirements for improvements to reporting mechanics in wdio and raise issue to make such features to main wdio repo as you did for afterTest hook.

**Comment by igerasimov23** [comment]
Lmk, if current after hook retry will not work  then we can get more information and create ticket with wdio team

**Comment by BorisOsipov** [comment]
Kk

**Comment by BorisOsipov** [comment]
I've done smth. But I don't have any projects to test it in real cases.

You can play with it in 
```
"wdio-reportportal-reporter": "git+https://github.com/BorisOsipov/wdio-reportportal-reporter#retry_experiments",
```

Add to afterTest hook:
```
    afterTest: function (test, context, { error, result, duration, passed, retries }) {
        // don't report retries when spec doesn't have retries
        if(test._retries === -1) {
            return
        }
		// don't report retries when it is last retry
        if(test._retries === test._currentRetry ) {
            return
        }
		// don't report retries when it is not failed - wdio will end test by itself
        if(test.error) {
            const data = {};
            data.error = "Retry exception string";
            reportportal.testRetry(data);
        }
    },
```

It is not final api. 

How it works.
Wdio send events to reporter:

```
1 Start suite:
2 	Start test
3	Start test - retry
4	Start test - retry
5	Finish test
6 Finish suite.
```
So I can't fail test in reporter cuz I don't have stacktrace.
To help reporter you have to call `reportportal.testRetry(data);` to stop current test and send data to rp.
```
1 Start suite:
2 	Start test
	Finish test - by reportportal.testRetry(data)
3	Start test 
	Finish test - by reportportal.testRetry(data)
4	Start test 
5	Finish test -by wdio event
6 Finish suite.
```

It is your own responsibility to call or not call `reportportal.testRetry(data);`.
I don't care about handling wrong calls. If you don't call `testRetry` - it just ignore this test retry result and dont report it to RP. If you call `testRetry` when it might not need you will have extra retries in report or just broken report. So it is up to you how to handle all cases.

`data` param should be an object with string field `error` - it will be sent to rp as error stacktrace

Will be nice if you can test it.
Let me know if you need more info.

**Comment by igerasimov23** [comment]
Thank you. Will test it on Monday and let you know for sure

**Comment by igerasimov23** [comment]
I tested quickly and it looks fine, but will deeply test it on Monday and plugin retry option to Jenkins to see how it will behave on large scale. 
P.S. we can also send failure message from afterTest hook:
```
if(test.error) {
      const data = {};
      data.error = test.error;
      reporter.testRetry(data);
    }
```

**Comment by BorisOsipov** [comment]
>I tested quickly and it looks fine

yes I made some tests and it works :)

> to see how it will behave on large scale.

Will be nice. Pay more attention to logs reporting, attaching screens, etc.
I haven't use retry features in RP ever, I didn't understand how to get logs\files from test retries from RP UI.

**Comment by BorisOsipov** [comment]
>P.S. we can also send failure message from afterTest hook:

Sure. But `test.error` strange object. I couldn't properly convert it to string...

**Comment by igerasimov23** [comment]
I've been testing retry option and it looks good from my point of view. Like you said `test.error` strange object. For now this is only way I found to pass error msg:
``` 
if (test.error) {
      const data = {};
      let obj = test.error;

      data.error = test.error
      reporter.testRetry(data);
    }
```
But it would be nice to pass whole stack trace object. Any thoughts?

**Comment by BorisOsipov** [comment]
> Any thoughts?

No ideas. I didn't get how to extract stacktrace from `test.error`. But it is strange that `console.log(test.error)` prints correct string.

Maybe you can get error form other hook params `afterTest: function (test, context, { error, result, duration, passed, retries }`?

**Comment by igerasimov23** [comment]
when I do 
``` 
afterTest: function (test, context, { error, result, duration, passed, retries }) {
console.log(error)
}
```
returns
```
{ Error: Test failed.
Reason: element 'settings button' is not visible
    at NavBarPage.waitAndClick (/Users/208821/Projects/np-cooking/api/test/e2e/pages/page.js:46:13)
    at NavBarPage.openSettingsPopover (/Users/208821/Projects/np-cooking/api/test/e2e/pages/navBarPage.js:91:10)
    at Context.<anonymous> (/Users/208821/Projects/np-cooking/api/test/e2e/test/features/header/test-header.js:30:12) name: 'Error' } 
```
and then
```
const data = {};
      data.error = error;
      reporter.testRetry(data);
```
in RP I see 
<img width="1482" alt="Screen Shot 2019-11-12 at 9 51 31 AM" src="https://user-images.githubusercontent.com/15241367/68681827-1c541e80-0532-11ea-993e-9b05eebb19eb.png">

any thoughts how to send stack-trace to RP as well?

**Comment by BorisOsipov** [comment]
Ilya, we found solution:
```
        if(test.error) {
            const data = {};
            data.error = JSON.stringify(test.error, Object.getOwnPropertyNames(test.error))
            reportportal.testRetry(data);
        }
```
My js guru friends pointed me to https://stackoverflow.com/questions/18391212/is-it-not-possible-to-stringify-an-error-using-json-stringify

Today I learnt smth new about js :)

**Comment by igerasimov23** [comment]
Thank you!!! Works well

**Comment by igerasimov23** [comment]
@BorisOsipov Are you planning to release new version with retry option in it?

**Comment by BorisOsipov** [comment]
Yes. Really busy now.

**Comment by BorisOsipov** [comment]
@igerasimov23 

I've published 5.2.3 with these changes. I don't mind make this public documented api. It is still crutches :(

So, pay attention I've renamed method

`reportportal.testRetry(test)` => `reportportal.finishTestManually(test)`

Also retries flag is disable by default. you must enable it by

```
const conf = {
...
setRetryTrue: true
...
};
```

It is because I don't know how RP detect retries... I guess, it done by test name and it can cause unexpected behaviour for some users.

Ilya, could you please test it and let me know that everything ok( I don't have enough time to check it myself)

**Comment by igerasimov23** [comment]
Thank you, will do it during this week and let you know. Thank you for creating 5.2.3

**Comment by igerasimov23** [comment]
I finished testing on my project and it looks fine. Have not notice any issues yet

**Comment by BorisOsipov** [comment]
ok. close then.

Thank you.
