### ISSUE TITLE
launch tags

### ISSUE THREAD

**Issue by hychiuatspireon** [BorisOsipov/wdio-reportportal-reporter#29]
## The problem

I would like to add tags to each launch to report portal. I tried to add a `tags` list within `wdio.config.js > reporterOptions > reportportal > rpConfig`, but it didn't seem to work. I can't see any tags added to the launch at the report portal side. Are launch tags supported by this library?

## Environment

* WebdriverIO version: 4.13.1
* wdio-reportportal-reporter version: 0.0.18
* Node.js version: 8.9.4
* WDIO Testrunner and version(mocha\cucumber\jasmine): mocha 5.0.0
* Additional wdio packages used (if applicable):

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by BorisOsipov** [comment]
@hychiuatspireon Fixed in 0.0.20. You can pass launch tags and description from config. See `rpConfig` section  [in readme](https://github.com/BorisOsipov/wdio-reportportal-reporter#configuration)
