### ISSUE TITLE
Reportportal never finishes session after webdriverIO suite were run

### ISSUE THREAD

**Issue by igerasimov23** [BorisOsipov/wdio-reportportal-reporter#3]
Reportportal never finishes session after webdriverIO suite were run- it shows `in progress` for *.js run

**Comment by BorisOsipov** [comment]
Hi @igerasimov23,

Yes it is. I can't fix it due wdio-reporter\rp-client architecture.
The only way is add some timeout after all test for waiting that all reportportal requests complete.
I use following in my wdio.conf.js
```
  async onComplete() {
    return new Promise(resolve => setTimeout(resolve, 5000));
  },
```
