### ISSUE TITLE
Error 4001. Limitation of test.title length (less than 256 symbols)

### ISSUE THREAD

**Issue by vostvesh** [BorisOsipov/wdio-reportportal-reporter#31]
## The problem

Error with creation test item on report portal when test.title have length above 256 symbols.

## Environment

* WebdriverIO version: ^4.14.0
* wdio-reportportal-version version: ^0.0.17
* Node.js version: 10.13.0
* WDIO Testrunner and version(mocha\cucumber\jasmine): mocha ^5.2.0

## Details

I think we could add a check of the test title length in the testStart(test) function.
Like this:

 public testStart(test) {
....
    if (test.title.length > 256) {
      test.title = test.title.slice(0, 255);
    }
....
}

## Code To Reproduce Issue

code: 
it('Some text with string length above 256 symbols....', () => {});

error: 
{ error_code: 4001,
  message:
   'Incorrect Request. [Field \'name\' should have size from \'1\' to \'256\'.] ' }

**Comment by BorisOsipov** [comment]
@vostvesh Thanks for reporting this. Fixed in 0.0.19
