### ISSUE TITLE
Test shows as PASSED but when navigating to test itself it is FAILED

### ISSUE THREAD

**Issue by igerasimov23** [BorisOsipov/wdio-reportportal-reporter#4]
Test shows as PASSED in test spec (on *.js) but when navigating to test itself it shows status is FAILED

**Comment by BorisOsipov** [comment]
May add screenshots from your rp launch? I didn't catch what do you mean.

**Comment by igerasimov23** [comment]
images attached
<img width="1375" alt="screen shot 2018-09-26 at 10 46 36 am" src="https://user-images.githubusercontent.com/15241367/46088090-ad730500-c179-11e8-93c7-8a68a61883b6.png">

<img width="1373" alt="screen shot 2018-09-26 at 10 46 25 am" src="https://user-images.githubusercontent.com/15241367/46088102-b2d04f80-c179-11e8-9e8a-e6f6ef7cea46.png">

**Comment by BorisOsipov** [comment]
Ok got it. Will see.
May you also share this test code?
You may delete all code expect describe()\it() calls

Like this: 
```
describe('Some suite', () => {
  before(()=>{
	//do smth
  });

  it('some tests', () => {
	//do smth
  });
});
```

**Comment by BorisOsipov** [comment]
@igerasimov23 Sorry, can't reproduce. can you share code?

**Comment by igerasimov23** [comment]
I will close issue as it happened when test suite was not completed. I implemented hack to wdio from your suggestion and don't see this issue anymore. Everything displays as expected
