### ISSUE TITLE
Multiple instances - browserName on feature level

### ISSUE THREAD

**Issue by SomersBjorn** [BorisOsipov/wdio-reportportal-reporter#44]
## The problem

The used browserName is not visible in the reportPortal on feature (or Suite) level.

## Environment

* WebdriverIO version: 4.12
* wdio-reportportal-version version: 0.22
* wdio-cucumber-framework

## Details

When you ran a test with multiple instances then there is a distinction on the used browsers in the reportPortal. You’ll see multiple features with the same name, but the used browser is not visible unless you check the tests inside that feature.

Is there a way to have the browserName send to the feature tag (or description)?

**Comment by BorisOsipov** [comment]
> test with multiple instances 

how you capabilties looks like in wdio config?

**Comment by SomersBjorn** [comment]
for example:

capabilities: [
    {
      browserName: 'chrome',
      maxInstances: '1',
      platform: 'MAC',
      chromeOptions: { args: ['--headless', '--disable-gpu', 'disable-infobars'] },
    },
    {
      browserName: 'firefox',
      maxInstances: '1',
      marionette: true,
      platform: 'MAC',
      'moz:firefoxOptions': { args: ['-headless'] },
    },
  ],

**Comment by BorisOsipov** [comment]
1) I am not crazy about this feature because only `browserName` is not enough(we ran into this issue in wdio-allure-reporter) - you can run tests with the same `browserName`, but different `version` \ `platform` - so you can't identify tests by `browserName` only.
Also it is not cover cases with mobile devices where is `deviceName` appears.

2) is it really need to add this to tags(to allow filtering)?

**Comment by SomersBjorn** [comment]
Is there a way for myself to send it to reportPortal, via a function (like the "sendToReporter") that I can add in my before hook?
This indeed might not be a super needed feature for everyone :)

**Comment by BorisOsipov** [comment]
No, I guess it is hard to implement. I will think how deal with it.

**Comment by BorisOsipov** [comment]
@SomersBjorn 
![image](https://user-images.githubusercontent.com/6514276/52572418-d1816b00-2e28-11e9-9c57-6059568dbaad.png)

does it look like you want to have?

**Comment by SomersBjorn** [comment]
@BorisOsipov 
From the looks of it, this would be perfect for me. :)

**Comment by BorisOsipov** [comment]
@SomersBjorn ok can you check on `wdio-reportportal-reporter@0.0.23`?

**Comment by SomersBjorn** [comment]
@BorisOsipov , I've just tested version 0.0.23 on 3 browsers and for me it works perfectly.
- The browserName, version & platform capability are displayed in the description of the feature and in the description of the scenario.
- The steps are still populated like they were, with the browser parameters

![image](https://user-images.githubusercontent.com/40167863/52619006-bf431380-2ea0-11e9-8587-eb050f20f69b.png)

![image](https://user-images.githubusercontent.com/40167863/52618978-a9cde980-2ea0-11e9-9fe9-4108e5cc139f.png)

**Comment by BorisOsipov** [comment]
ok, thanks. close then.
