### ISSUE TITLE
Cannot find module 'reportportal-client' in Drone if package-lock file is checked in

### ISSUE THREAD

**Issue by prathameshnyt** [BorisOsipov/wdio-reportportal-reporter#47]
## The problem

Thank you so much for this feature. It's super helpful.

We are getting "Error: Cannot find module 'reportportal-client" error while running tests from drone if I checked in a package-lock file. It works fine locally as well as from drone if I don't check-in package-lock. 

Do you think changing dependency might have caused this problem or maybe it's an issue with npm install? Can you please look into it?

https://github.com/BorisOsipov/wdio-reportportal-reporter/commit/b7e14bda3b6e8f51c1adb4a609af9791024ef00e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2  

## Environment

* WebdriverIO version: 4.11.0
* wdio-reportportal-version version: .0.0.22
* Node.js version:
* WDIO Testrunner and version(mocha\cucumber\jasmine): mocha
* Additional wdio packages used (if applicable):

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by BorisOsipov** [comment]
hi @prathameshnyt 

>if I don't check-in package-lock.

What do you mean? Shall I ask you to share how your package-lock looks like by gist or pastebin snippet?

**Comment by prathameshnyt** [comment]
Please find here - https://gist.github.com/prathameshnyt/c59de2fa674f8df9c372ac4fa0729141 

If I add "reportportal-client": "https://github.com/reportportal/client-javascript.git#b09e49b", explicitly again in my defense with "wdio-reportportal-reporter": "^0.0.22", then it works fine with package-lock as well.

**Comment by BorisOsipov** [comment]
@prathameshnyt can you set in your `package.json` fixed version `"wdio-reportportal-reporter": "0.0.22"`, run `npm i` to generate lock file and commit both new `package.json` and `package-lock.json`? I don't have ideas why droneci can't download deps...

**Comment by prathameshnyt** [comment]
Ok. I did that. I am using a fixed version of "wdio-reportportal-reporter": "0.0.22" Thanks.

**Comment by BorisOsipov** [comment]
Ok close then
