### ISSUE TITLE
Does not send screenshot to ReportPortal on failure

### ISSUE THREAD

**Issue by igerasimov23** [BorisOsipov/wdio-reportportal-reporter#6]
## The problem

plugin does not send screenshot to reportportal for failed test
## Environment

* WebdriverIO version: 4.11
* wdio-reportportal-version version: 0.7
* Node.js version: v8.11.12
* WDIO Testrunner and version(mocha\cucumber\jasmine): mocha

## Code To Reproduce Issue [ Good To Have ]
```
describe('test footer', function () {
    it('Verify footer is displayed -feature footer', function () {
        assert.isTrue(false)
    });
});
```
<img width="1359" alt="screen shot 2018-09-26 at 1 44 36 pm" src="https://user-images.githubusercontent.com/15241367/46098968-845f6e00-c193-11e8-9240-a6d2e2e6f296.png">

**Comment by BorisOsipov** [comment]
It can't be done by reporter itself.
You can implement it by executig reporter method from e.g. `afterTest` hook.
See https://github.com/BorisOsipov/wdio-reportportal-reporter#additional-api for details.
