### ISSUE TITLE
ReportPortal Launch Not Closing

### ISSUE THREAD

**Issue by garethleonard** [BorisOsipov/wdio-reportportal-reporter#61]
## The problem

The ReportPortal launch does not close after the test is complete

## Environment

* WebdriverIO version: 5.7.8
* wdio-reportportal-version version: 5.0.0
* Node.js version: 10.15.1
* WDIO Testrunner and version(mocha\cucumber\jasmine): Jasmine
* Additional wdio packages used (if applicable):

## Details

After the test run is complete the ReportPortal launch is not closed, it remains running and eventually times out.

## Code To Reproduce Issue [ Good To Have ]

```
const reportportal = require('wdio-reportportal-reporter');
const RpService = require('wdio-reportportal-service');

const conf = {
  reportPortalClientConfig: {
    token: process.env.RP_TOKEN,
    endpoint: 'http://localhost:8080/api/v1',
    launch: 'android',
    project: 'android',
    mode: 'DEFAULT',
    debug: false,
    description: `Android Test Automation`,
    tags: ['android']
  },
  reportSeleniumCommands: false,
  autoAttachScreenshots: false,
  seleniumCommandsLogLevel: 'debug',
  screenshotsLogLevel: 'info',
  parseTagsFromTestTitle: false
};
exports.config = {
  // ====================
  // Runner and framework
  // Configuration
  // ====================
  runner: 'local',
  framework: 'jasmine',
  jasmineNodeOpts: {
    defaultTimeoutInterval: 90000
  },
  sync: true,
  logLevels: 'silent',
  deprecationWarnings: true,
  bail: 0,
  waitforTimeout: 10000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  services: [[RpService, {}]],
  reporters: [[reportportal, conf]],
  // ====================
  // Some hooks
  // ====================
  beforeSession: (config, capabilities, specs) => {
    require('@babel/register');
  }
};
```

**Comment by BorisOsipov** [comment]
Hi @garethleonard thanks for feedback

1) are there any error logs?
2) could you please share repo with reproducable example it will help a lot.

**Comment by prathameshnyt** [comment]
Looks like I am also running into the same issue.  

1. Node - v10.15.2
2. WebdriverIO Version - 5.7.8
3. Framework- Mocha

We have `return new Promise(resolve => setTimeout(resolve, 5000));` in onComplete for v4 version and it worked fine. I have added same in v5 as well. 

Please check trace output [here](https://gist.github.com/prathameshnyt/e85c973f1323fe59bf422a989bcb2e8b). Hope it helps.

**Comment by BorisOsipov** [comment]
@prathameshnyt could you please share repo with reproducable

**Comment by prathameshnyt** [comment]
Thanks @BorisOsipov. As per your doc added 
`"wdio-reportportal-service": "5.0.0" ` in package.json and 

`const RpService = require("wdio-reportportal-service");`
services = ['selenium-standalone', [trsService, {}]];

in wdio.conf it worked fine. Is this expected behavior? I meant, do we need to now this service as well?

**Comment by BorisOsipov** [comment]
>Is this expected behavior? I meant, do we need to now add this service as well?

yes it is desribed in reporter docs.
