### ISSUE TITLE
Link to License is invalid

### ISSUE THREAD

**Issue by mgrybyk** [BorisOsipov/wdio-reportportal-reporter#65]
## The problem

1. Open https://github.com/BorisOsipov/wdio-reportportal-reporter/blob/master/README.md
2. Click [LICENSE.md](https://github.com/BorisOsipov/wdio-reportportal-reporter/blob/master/LICENSE.md)

**Actual Result**
404

**Expected Result**
Change url -> [LICENSE](https://github.com/BorisOsipov/wdio-reportportal-reporter/blob/master/LICENSE) or rename LICENSE file to LICENSE.md

**Comment by BorisOsipov** [comment]
Fixed, thanks
