### ISSUE TITLE
I have been using the latest version of reporter and service but I'm getting an error when I run my test suit:

### ISSUE THREAD

**Issue by BorisOsipov** [BorisOsipov/wdio-reportportal-reporter#68]
I have been using the latest version of reporter and service but I'm getting an error when I run my test suit:

![image](https://user-images.githubusercontent.com/36016665/60684143-5f123580-9e72-11e9-8f7f-e9e371ad0dbc.png)

This is my wdio config file (I have supressed some information about token and project):

```
const reportportal = require('wdio-reportportal-reporter');
const RpService = require("wdio-reportportal-service");

const conf = {
  reportPortalClientConfig: {
    token: 'my-token',
    endpoint: 'http://localhost:8080/api/v1',
    launch: 'TEST',
    project: 'my-project',
    tags: ["FUNCTIONAL"],
    mode: 'DEFAULT',
    debug: false,
  },
  reportSeleniumCommands: false,
  autoAttachScreenshots: false,
  seleniumCommandsLogLevel: 'debug',
  screenshotsLogLevel: 'info',
  parseTagsFromTestTitle: false,
};

exports.config = {
  runner: 'local',
  hostname: 'localhost',
  port: 4444,
  path: '/wd/hub',
  specs: [
    './test/specs/**/*.js'
  ],
  maxInstances: 10,
  capabilities: [{
    maxInstances: 5,
    browserName: 'chrome',
  }],
  logLevel: 'info',
  bail: 0,
  baseUrl: 'http://automationpractice.com',
  waitforTimeout: 10000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  framework: 'mocha',
  services: [[RpService, {}]],
  reporters: [[reportportal, conf]],
  mochaOpts: {
    ui: 'bdd',
    timeout: 60000
  }
}
```

Find bellow the dependencies of my project:

```
"devDependencies": {
    "@wdio/cli": "^5.10.9",
    "@wdio/local-runner": "^5.10.9",
    "@wdio/mocha-framework": "^5.10.8",
    "@wdio/sync": "^5.10.8",
    "chromedriver": "^75.0.0",
    "wdio-reportportal-reporter": "^5.0.1",
    "wdio-reportportal-service": "^5.0.1"
  }
```

_Originally posted by @luuizeduardo in https://github.com/BorisOsipov/wdio-reportportal-reporter/issues/1#issuecomment-508556094_

**Comment by BorisOsipov** [comment]
@luuizeduardo you get error but launch and test data appears in report portal right?

is there full error stack trace?

**Comment by luuizeduardo** [comment]
> @luuizeduardo you get error but launch and test data appears in report portal right?

@BorisOsipov This is right, the test data appears, but the launch doesn't seem to be completed. Find bellow the full stack trace:

<img width="1087" alt="Screen Shot 2019-07-04 at 15 55 42" src="https://user-images.githubusercontent.com/36016665/60684490-5f133500-9e74-11e9-8c13-241be463c5c5.png">

**Comment by BorisOsipov** [comment]
@luuizeduardo your config looks correct. 

I guess there is some issue with changes in wdio packages. 
I will update my project tommorow and fix\file a bug for main wdio repo.

It will really help if you check for me, does error appear if you downgrade to
```
	"webdriverio": "5.7.9",
    "@wdio/cli": "^5.9.6",
    "@wdio/local-runner": "^5.9.6",
    "@wdio/mocha-framework": "^5.9.4",
    "@wdio/spec-reporter": "^5.9.3",
    "@wdio/sync": "^5.9.6",
```
please don't forget about package-lock* files :)

**Comment by luuizeduardo** [comment]
I've downgraded and the error  still appears in this version.
PS: I removed the `package-lock.json` of my project to guarantee that the downgrade was properly executed.

**Comment by dragancla** [comment]
I've got the same thing:

```
[0-0] Logging the reportportalConfig object: 
{ reportPortalClientConfig:
   { token: 'xx',
     endpoint: 'http://xx/api/v1',
     launch: 'v5_test',
     project: 'xx',
     mode: 'DEFAULT',
     debug: false,
     description: 'Test is run on branch  for commit ',
     tags: [ 'local:false', 'branch:', 'commit:' ] },
  reportSeleniumCommands: false,
  autoAttachScreenshots: false,
  seleniumCommandsLogLevel: 'debug',
  screenshotsLogLevel: 'info',
  parseTagsFromTestTitle: false }

2019-07-08T15:06:57.363Z ERROR @wdio/cli:utils: A service failed in the 'onComplete' hook
Error: Launch "fd2eln1e6sjxuiqtro" not found
    at RPClient.finishLaunch (/Users/myrepo/node_modules/reportportal-js-client/lib/report-portal-client.js:169:55)
    at RpService.onComplete (/Users/myrepo/node_modules/wdio-reportportal-service/src/index.js:26:51)
    at Promise.all.launcher.map.service (/Users/myrepo/node_modules/@wdio/cli/build/utils.js:32:33)
    at Array.map (<anonymous>)
    at runServiceHook (/Users/myrepo/@wdio/cli/build/utils.js:30:39)
    at Launcher.run (/Users/myrepo/node_modules/@wdio/cli/build/launcher.js:96:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Continue...
```

**Comment by BorisOsipov** [comment]
Yeah reproduced it with a new sample project. It is definitely some breaking change from wdio cuz it works like charm in my old project with old deps.

Will prepare fix soon.

**Comment by dragancla** [comment]
Thanks for maintaining this 😀 Really appreciate it

**Comment by BorisOsipov** [comment]
@luuizeduardo @dragancla fixed in wdio-reportportal-service 5.0.2. Could you please check?

**Comment by dragancla** [comment]
Seems to be working, thank you so much for fixing it!

**Comment by BorisOsipov** [comment]
Thanks. Close then
