### ISSUE TITLE
With webdriverIO V5 wdio-reporter does not report selenium logs

### ISSUE THREAD

**Issue by igerasimov23** [BorisOsipov/wdio-reportportal-reporter#73]
## The problem

After Updating to WebdriverioV5 and using "wdio-reportportal-reporter": "5.0.1", we don't see selenium logs
My config:
``` 
reportPortalClientConfig: {
    token: reportPortalUUID,
    endpoint: 'https://testreportingsystem-api.nyt.net/api/v1',
    launch: process.env.JOB_NAME,
    project: 'cooking',
    mode: 'DEFAULT',
  },
  enableSeleniumCommandReporting: true,
  enableScreenshotsReporting: false,
  seleniumCommandsLogLevel: 'debug',
  screenshotsLogLevel: 'info',
  enableRetriesWorkaround: true,
  parseTagsFromTestTitle: true,
  debug: false,
```

## Environment

* WebdriverIO version: 5.10.7
* wdio-reportportal-version version: 5.0.1
* Node.js version: 10.16.0
* WDIO Testrunner and version(mocha\cucumber\jasmine): Mocha
* Additional wdio packages used (if applicable):

**Comment by BorisOsipov** [comment]
![image](https://user-images.githubusercontent.com/6514276/61889106-7b534080-af0d-11e9-8e02-3b042ab4112e.png)
Logs are reported well.

>enableSeleniumCommandReporting: true,

is obsolete.
update your config according https://github.com/BorisOsipov/wdio-reportportal-reporter#configuration
there is some changes in options names

**Comment by igerasimov23** [comment]
Thank you. Did not realize those changes
