### ISSUE TITLE
Support for report portal v5

### ISSUE THREAD

**Issue by BorisOsipov** [BorisOsipov/wdio-reportportal-reporter#74]
## The problem

Make reporter compatible with report portal v4 and v5

**Comment by drptbl** [comment]
ReportPortal v5 error:
```
Error: Request failed with status code 400: {"errorCode":4001,"message":"Incorrect Request. [Field 'startTime' should not be null.] "}
    at axios.then.catch (/home/node/app/node_modules/reportportal-js-client/lib/rest.js:27:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by BorisOsipov** [comment]
Fixed and did some test. 

You can try it with beta versions:
```
"wdio-reportportal-reporter": "5.1.0-beta",
"wdio-reportportal-service": "5.1.0-beta"
```
This versions should work with report portal v5 and v4.

**Comment by BorisOsipov** [comment]
@drptbl did you have a chance to test this? Any issues?

**Comment by drptbl** [comment]
@BorisOsipov Yes, I'm confirming that it's working with simple setup. I've seen some issues thrown while for example there was a JSON printed on error and when report portal reporter wanted to send it there was some errors in console, however I didn't had enough time yet to test it properly.

**Comment by jpaolini** [comment]
@BorisOsipov I've been testing this out as well.  Report Portal is still new to me thought.  I'm using cucumber and in my afterStep hook, I have the following code
```
const { status } = result;

    if (status === 'failed') {
      const { text, keyword } = step;

      const failureObject = {
        type: 'afterStep',
        title: `${keyword} ${text}`
      };

      const screenshot = browser.takeScreenshot();
      const attachment = Buffer.from(screenshot, 'base64');
      reportportal.sendFileToTest(failureObject, 'error', 'screenshot.png', attachment);
    }
```
I'm not able to view the attachment in Report Portal.

The second thing I noticed is that the launch still shows as running in Report Portal even thought it's completed. 

I'm diving into the code now to see if I can spot anything.

**Comment by BorisOsipov** [comment]
@drptbl thanks. I'm looking forward to your feedback in the future

**Comment by BorisOsipov** [comment]
@jpaolini I am not cucumber user. For your code example only one remark from me:
Change ``title: `${keyword} ${text}`` to title: ``${keyword}${text}`` (remove space)
I guees @tamil777selvan can give you some advice about cucumber integration

>The second thing I noticed is that the launch still shows as running in Report Portal even thought it's completed.

do you use report portal v5 or v4? for v4 it is known issue... some times launch isn't closed by unknown reasons.

**Comment by jpaolini** [comment]
@BorisOsipov, oh man, changing it to `${keyword}${text}` fixed that issue!  awesome stuff!  I'm using Report Portal v5, very new with it, just started a few days ago.  Thank you!  I'll post if I find anything with the launch issue.

**Comment by BorisOsipov** [comment]
@jpaolini 
>I noticed that the auto save screenshot doesn't appear to be working.

1) it is strange. As I know it worked when I've tested. I don't have access to report portal v5 instance to check\fix it now. If you can share some testing instance for me, please share with me server address\credentials via email: osipov.boris@gmail.com or by gitter

2) report portal v5 is still beta. I am waiting for next beta\alpha\final release with stable API to make stable reporter version with new report portal api

3) it will be fine if you can share some repo on github with your code to reproduce this issue

**Comment by BorisOsipov** [comment]
>All of the stuff I have is locked by my company

Sure, I realise this, no problems.

>I'll try to get a working example or something like that this week.

will be nice. thanks!

**Comment by BorisOsipov** [comment]
Release as

"wdio-reportportal-reporter": "5.2.2",
"wdio-reportportal-service": "5.2.2"
