### ISSUE TITLE
Print link to report portal launch at the end of test run

### ISSUE THREAD

**Issue by BorisOsipov** [BorisOsipov/wdio-reportportal-reporter#82]
Print link to report portal launch at the end of test run

**Comment by jpaolini** [comment]
@BorisOsipov, Just to confirm, this would be writing a link to the console to the specific launch or just to Report Portal login page?

**Comment by BorisOsipov** [comment]
Link to the launch

**Comment by igerasimov23** [comment]
It would be very nice not just print this link to console but to have an option control of it such as
`reportPortal.getLaunchUrl()`

and then we can push it to Slack or send email if we need to.

**Comment by BorisOsipov** [comment]
>reportPortal.getLaunchUrl()
>and then we can push it to Slack or send email if we need to.

yeah, good idea. Will see how we can solve this.

**Comment by BorisOsipov** [comment]
Added in `wdio-reportportal-service:5.2.2`

See some docs:
https://github.com/BorisOsipov/wdio-reportportal-reporter#getting-link-to-report-portal-ui-launch-page

**Comment by BorisOsipov** [comment]
@igerasimov23 it will be nice if you can check how it work for your environment. I tested it with demo stands, but maybe there are some issues in link generation.

Thanks in advance.

**Comment by igerasimov23** [comment]
I tested and implemented already and it works fine. I see it builds url based on `reportPortalClientConfig` in my case I needed to do some trimming as my end point looks like this `endpoint: 'https://testreportingsystem-api.nyt.net/api/v1',` I just removed '-api` from it and it redirects to correct url after that

**Comment by BorisOsipov** [comment]
I've worried about some issues with inconsistent urls. Nice. Thank you for your feedback!
