### ISSUE TITLE
Feature request: suite tags support

### ISSUE THREAD

**Issue by dragancla** [BorisOsipov/wdio-reportportal-reporter#83]
Feature request:
Report portal API supports adding tags to the suite. Can we extend functionality of wdio-reportportal-reporter?

Just like in this issue: https://github.com/BorisOsipov/wdio-reportportal-reporter/issues/19

But parsing tags from suite names (describe) not just test names (it)

**Comment by BorisOsipov** [comment]
yes, why not

**Comment by BorisOsipov** [comment]
@dragancla Added it. Could you please test it with `"wdio-reportportal-reporter": "5.0.2"`?
Feature can be enabled\disabled by the same option `parseTagsFromTestTitle`

**Comment by BorisOsipov** [comment]
@dragancla any news?

**Comment by dragancla** [comment]
Just came back from vacation, gimme a few mins

**Comment by dragancla** [comment]
Yes, it is working, thanks!
