### ISSUE TITLE
Question: Automatically merge launches

### ISSUE THREAD

**Issue by gromanas** [BorisOsipov/wdio-reportportal-reporter#85]
Hello! We have started using the report portal in our project. We have the case that in the pipeline we have one step that triggers a suite of tests and in another step, it triggers another suite of tests. Both of them start different launches. I wanted to ask if there is a possibility to automatically merge those two launches.

**Comment by BorisOsipov** [comment]
> if there is a possibility to automatically merge those two launches.

RP suports launch merge feature, but you should know launch ids. So can you save somewhere(file, env variables) ids and share it for final pipeline step to merge launches?

**Comment by gromanas** [comment]
Yes, I could save them as env variables

**Comment by gromanas** [comment]
Can you please give me some more context? Thank you in advance

**Comment by BorisOsipov** [comment]
you can check report portal api docs about `POST /launche/merge` method
