### ISSUE TITLE
Plugin reports Test Passed if before hook fails webdriverIO v5

### ISSUE THREAD

**Issue by igerasimov23** [BorisOsipov/wdio-reportportal-reporter#88]
## The problem

If test fails in Before hook plugin reports to RP as test passed

## Environment

* WebdriverIO version: 5.11.13
* "wdio-reportportal-reporter": "5.0.1",
* "wdio-reportportal-service": "5.0.2",
* Node.js version: v10.16.0
* WDIO Testrunner and version(mocha\cucumber\jasmine): mocha
* Additional wdio packages used (if applicable):
## Code To Reproduce Issue [ Good To Have ]

```
describe('test', function () {

  before( function () {
    assert.isTrue(false, 'before hook failed')
  })
  
  it('Verify test 1', () => {
    browser.url('some url');
    assert.isTrue(true, 'test passed')
  })
});
 ````

Similar to what was fixed: https://github.com/BorisOsipov/wdio-reportportal-reporter/issues/24

**Comment by BorisOsipov** [comment]
Hi, checked by test repo 
https://github.com/BorisOsipov/wdio-v5-jasmine/blob/v5_testing/specs/sample.spec.js#L29

On rp side see

![image](https://user-images.githubusercontent.com/6514276/67142763-1ccc0300-f26d-11e9-9eea-cfd5669125d4.png)

Seems ok.
I use wdio `~5.15.1`

can you check or\and provide more details?

**Comment by igerasimov23** [comment]
Hey, may be I'm missing here something. I definitely see the same as you but if you go level up you will see:
 
<img width="1453" alt="Screen Shot 2019-10-19 at 9 06 17 AM" src="https://user-images.githubusercontent.com/15241367/67145458-d1efc280-f24f-11e9-9971-ad86975848de.png">

It does not show if test passed or failed, besides to investigate in right corner? 
Is it expected behavior?

**Comment by BorisOsipov** [comment]
I don't know.
It is how RP shows result in case when tests aren't started when before hook failed.

For me it is strange but ok. You see exactly what happened - no test were ran in suite because some error in before hook..

**Comment by igerasimov23** [comment]
Thank you. Closing issue
